version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install openssl
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Decrypt server key
          command: openssl aes-256-cbc -d -in server-cipher -out server.key -k $encryption_key
      - run:
          name: Print the Current Time
          command: date