version: 2
dependencies:
  pre:
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Openssl
          command: apt-get update; apt-get install -y openssl=1.0.2g
      - run:
          name: Decrypt server key
          command: openssl aes-256-cbc -d -in server-cipher -out server.key -k $encryption_key
      - run:
          name: Print the Current Time
          command: date